spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/vkstatsdb?useLegacyDatetimeCode=false}
    useJDBCCompliantTimeZoneShift: true
    serverTimezone: Asia/Tokyo
    username: root
    password: testtest
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Tokyo
        dialect: org.hibernate.dialect.MySQL8Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

client:
  secret: # secret_code_from_vk_for_app
  id: # app_id_from_vk
server:
  host: # host_for_the_app (same host as redirect_url must be set at the VK app settings)
timeout:
  before_start_db_update: 5000
  db_update: 1000000
  to_get_data_from_vk_ms: 250
  clear_db_ms: 100
default:
  max_posts_count: 20
  offset: 0